---
- name: Simple playbook to print hostname
  host: all
  tasks:
    - name: Get hostname
      ansible.builtin.command:
        cmd: hostname
      register: hostname_result

    - name: Print hostname
      debug:
        msg: "The hostname is: {{ hostname_result.stdout }}"
